export default {
  "intro": [
    "Ace,",
    "Breaking news,",
    "By the way,",
    "Can I just say,",
    "Champ,",
    "Check it:",
    "Check this out,",
    "Dang...",
    "Everybody says",
    "Excuse me, but",
    "Experts agree:",
    "Fact:",
    "Fun fact,",
    "Get this,",
    "Girl,",
    "Guess what?",
    "Heads up,",
    "Hear ye, hear ye:",
    "Hey, you!",
    "Honestly,",
    "In my opinion,",
    "Just saying...",
    "Know this:",
    "Lean in,",
    "Let's be clear,",
    "Listen up,",
    "News alert:",
    "No joke,",
    "Okay, listen up:",
    "Real talk,",
    "Self,",
    "Spoiler alert,",
    "Superstar,",
    "Tiger,",
    "Truth bomb,",
    "Wait for it…",
    "Word on the street is,",
    "You ready for this?",
  ],
  "attribute": [
    "all of y'all",
    "every thought you have",
    "everything you do",
    "that brain of yours",
    "that saucy personality",
    "that sparkle in your eye",
    "the essential you",
    "the fire in your heart",
    "the mere idea of you",
    "the sparkle in your eye",
    "the way you handle things",
    "the way you roll",
    "the way you show up",
    "what you got going on",
    "whatever your secret is",
    "your authenticity",
    "your choice of attire",
    "your courage",
    "your creativity",
    "your determination",
    "your DNA",
    "your energy",
    "your genius",
    "your hair today",
    "your hard work",
    "your kindness",
    "your laugh",
    "your life's journey",
    "your moves",
    "your perseverance",
    "your personal style",
    "your presence here",
    "your resilience",
    "your sense of humor",
    "your soul",
    "your swagger",
    "your whole vibe",
  ],
  "praise": [
    "breeds miracles,",
    "could light up a galaxy,",
    "could move mountains,",
    "could write history,",
    "deserves a medal,",
    "deserves the Nobel prize,",
    "gets the party hopping,",
    "has no limits,",
    "has serious game,",
    "is 100% legit,",
    "is a national treasure,",
    "is a rainbow factory,",
    "is an unstoppable force,",
    "is awe-inspiring,",
    "is gold standard,",
    "is jaw-dropping,",
    "is made of diamonds,",
    "is out of this world,",
    "is paying off big time,",
    "is poetry in motion,",
    "is pure magic,",
    "is the next big thing,",
    "is the stuff of legends,",
    "is worth a standing ovation,",
    "just shimmers,",
    "makes birds sing,",
    "makes my world go 'round,",
    "makes the sun jealous,",
    "makes waves,",
    "radiates power,",
    "rains magic,",
    "raises the roof,",
    "roars like a lion,",
    "sets the standard,",
    "shines like a supernova,",
    "should be taught in school,",
    "shows mad skills,",
    "turns heads,",
  ],
  "finisher": [
    "24/7!",
    "according to CNN!",
    "an that's a fact!",
    "and that's on you.",
    "and you can't teach that.",
    "and you know it.",
    "can I get an amen?",
    "case closed.",
    "deal with it.",
    "don't fight it.",
    "don't forget it.",
    "drop the mic.",
    "end of story.",
    "facts only.",
    "for reals!",
    "full stop.",
    "high five!",
    "just saying.",
    "mic drop!",
    "no cap.",
    "nothing else matters.",
    "now let's dance!",
    "period.",
    "remember this.",
    "say it again!",
    "snuggle bear!",
    "so get used to it!",
    "so treat yourself!",
    "tell the world!",
    "that's just science!",
    "that's the truth.",
    "think about it.",
    "word!",
    "would I lie?",
    "write it down.",
    "you feel me?",
    "you heard me.",
    "you hidden gem!",
  ]
}